apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-app-exporter.secretName" . }}
  labels:
    {{- include "azure-app-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  azure-client-id: {{ .Values.azure.client.id | default "-unset-" | b64enc | quote }}
  azure-client-secret: {{ .Values.azure.client.secret | default "-unset-" | b64enc | quote }}
  azure-tenant-id: {{ .Values.azure.tenant | default "-unset-" | b64enc | quote }}
